### ISSUE TITLE
need change in SimulationConfiguration.java

### ISSUE THREAD

**Issue by zsharifian** [dsg-titech/simblock#19]
Hi
I think we should replace CBR_FAILURE_BLOCK_SIZE_DISTRIBUTION_FOR_CONTROL_NODE values with CBR_FAILURE_BLOCK_SIZE_DISTRIBUTION_FOR_CHURN_NODE values.
thanks

**Comment by nagayamaryu** [comment]
Hi, zsharifian.
Thank you for opening this issue.
I fixed this bug.
